### ISSUE TITLE
Failed to connect error. v1.12.1. Ubuntu 23.10

### ISSUE THREAD

**Issue by victor1234** [Jigsaw-Code/outline-client#1785] opened 2023-11-15 12:57 UTC
**Describe the bug**
After the system boots, the connection is automatically established (according to ipleak.net). But in the client the status is _Disconnected_. When you click on _CONNECT_, an error is displayed (in the screenshot)

**To reproduce**
Boot and click _CONNECT_

**Screenshots**
![Screenshot from 2023-11-15 15-48-05](https://github.com/Jigsaw-Code/outline-client/assets/1102205/3be62388-f407-4252-8dca-d630bb26ce25)

**Client system (please complete the following information):**
 - Outline Client: Linux  v1.12.1 (471860)
 - Your Operating System: Ubuntu 23.10

**Submit feedback**
_Submitted_

**Comment by maddyhof** [comment] 2023-11-20 16:11
Closing as a duplicate of https://github.com/Jigsaw-Code/outline-client/issues/1778

**Closed as not planned by maddyhof** 2023-11-20 16:11 UTC
Labels: bug
