### ISSUE TITLE
I have a error on WIN7 when i used the latest version

### ISSUE THREAD

**Issue by daddy2000** [Jigsaw-Code/outline-client#415] opened 2018-12-03 09:21 UTC
The problem was on win7 X64 like #251 on version 1.2.20 。The error words is “Not able to configure routing tables successfully”。And there’s no error on version 1.2.14 and 1.2.19。But outline-client will auto-upgrade to version 1.2.20 when i close this application。Is there anybody can help me？

**Comment by daddy2000** [comment] 2018-12-03 10:30
Is there any way can let me do not update to 1.2.20？So anxious for help。。。

**Comment by TabPaD** [comment] 2018-12-03 14:34
I just switched back to windows 7 because of some conflicts of nvidia driver with windows 10 and now I can't connect to outline server. The error says We were not able to configure your routing tables successfully. the installation of windows is fresh and I also tried installing Microsoft Visual C++ 2015 Redistributable Update 3 and .NET Framework 4.6.2 as @sean3r [commented on Oct 16 ](https://github.com/Jigsaw-Code/outline-client/issues/251#issuecomment-430203723) and the problem still exists.
the output of route print is:

**Comment by lgg** [comment] 2018-12-04 00:36
+1
same WiFi network: ios client connects successfully, win7 can't configure routing tables.

**Comment by lgg** [comment] 2018-12-04 01:19
Tried just now using Cygwin:
```
git clone https://github.com/Jigsaw-Code/outline-client && cd outline-client```
yarn
yarn do electron/run
```

Install Outline v1.2.20 and configure TAP-adapter manually(previously after this Outline works fine)

Outline client appers, I tried to connect to server:
```
skipping server migration, localstorage already exists
loading web app from file:///D:/dev/temp3/outline-client/build/windows/www/electron_index.html?debug=true
Outline is starting
Pipe connected
Got data from pipe
Pipe connected
Got data from pipe
could not connect: ConfigureSystemProxyFailure (OutlineService says: could not launch smartdnsblock at C:\Program Files (x86)\Outline\smartdnsblock.exe: Не удается найти указанный файл (network config: outline-tap0 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, Беспроводное сетевое соединение 2 (Down): 1 x ipv4 gateways, 0 x ipv6 gateways, Подключение по локальной сети (Down): 0 x ipv4 gateways, 0 x ipv6 gateways, Беспроводное сетевое соединение 2 (Down): 0 x ipv4 gateways, 0 x ipv6 gateways, Беспроводное сетевое соединение (Up): 1 x ipv4 gateways, 0 x ipv6 gateways, VirtualBox Host-Only Network (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, VirtualBox Host-Only Network #2 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, VMware Network Adapter VMnet1 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, VMware Network Adapter VMnet8 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, Loopback Pseudo-Interface 1 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, isatap.{B9CED3F0-B86D-4EAD-80F0-F32584039EAB} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{7E81B5EF-EA41-4068-A473-D6E2D0115D16} (Down): ipv4 disabled, 0 x ipv6 gateways, Teredo Tunneling Pseudo-Interface (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{D0816386-66BB-45BA-937A-934DF4A6B9DC} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{DDDDF1B8-3494-48A6-94AA-A6FB4C2B11FE} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{FB8BDE66-2683-4AB3-BE2C-7CBD401859C2} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{B5AA5A74-4449-499E-BB66-79A343A201D7} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{6F28D93D-11A1-4EF5-AC6A-685F131D2998} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{E57475E9-AD97-47CA-9FEF-FBB2BBFAC46C} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{E06E1AF9-4009-4390-A159-EA7D8CC5F464} (Down): ipv4 disabled, 0 x ipv6 gateways))
tun2socks exited with signal SIGTERM
ss-local exited with signal SIGTERM
Promise "DNS lookup" resolved before 10000 ms.
Promise "Reachability check" resolved before 10000 ms.
```

>C:\Program Files (x86)\Outline\smartdnsblock.exe: Не удается найти указанный файл (network config: outline-tap0
Can't find such file

Checked `C:\Program Files (x86)\Outline\` and...
My antivirus blocked this file -___-

![image](https://user-images.githubusercontent.com/12018713/49411933-c270a380-f77b-11e8-9395-c50a5dd0cade.png)

**Comment by lgg** [comment] 2018-12-04 02:43
Here English output:
```
loading web app from file:///D:/dev/temp3/outline-client/build/windows/www/electron_index.html?debug=true
Outline is starting
Pipe connected
Got data from pipe
Pipe connected
Got data from pipe
could not connect: ConfigureSystemProxyFailure (OutlineService says: smartdnsblock failed (stdout: found outline-tap0 at index 37
connected to filtering engine
created filtering sublayer
port 53 blocked with filter 432963
whitelisted traffic on outline-tap0 with filter 432964
Press any key to continue . . . , (stderr: ) (network config: outline-tap0 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, Беспроводное сетевое соединение 3 (Down): 0 x ipv4 gateways, 0 x ipv6 gateways, Беспроводное сетевое соединение 2 (Up): 1 x ipv4 gateways, 0 x ipv6 gateways, Подключение по локальной сети (Down): 0 x ipv4 gateways, 0 x ipv6 gateways, Беспроводное сетевое соединение (Down): 0 x ipv4 gateways, 0 x ipv6 gateways, VirtualBox Host-Only Network (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, VirtualBox Host-Only Network #2 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, VMware Network Adapter VMnet1 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, VMware Network Adapter VMnet8 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, Loopback Pseudo-Interface 1 (Up): 0 x ipv4 gateways, 0 x ipv6 gateways, isatap.{7E81B5EF-EA41-4068-A473-D6E2D0115D16} (Down): ipv4 disabled, 0 x ipv6 gateways, Teredo Tunneling Pseudo-Interface (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{6F28D93D-11A1-4EF5-AC6A-685F131D2998} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{B5AA5A74-4449-499E-BB66-79A343A201D7} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{D0816386-66BB-45BA-937A-934DF4A6B9DC} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{E06E1AF9-4009-4390-A159-EA7D8CC5F464} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{DDDDF1B8-3494-48A6-94AA-A6FB4C2B11FE} (Down): ipv4 disabled, 0 x ipv6 gateways, isatap.{E57475E9-AD97-47CA-9FEF-FBB2BBFAC46C} (Down): ipv4 disabled, 0 x ipv6 gateways))
ss-local exited with signal SIGTERM
tun2socks exited with signal SIGTERM
Promise "DNS lookup" resolved before 10000 ms.
Promise "Reachability check" resolved before 10000 ms.


```

**Comment by trevj** [comment] 2018-12-05 13:51
@daddy2000 @TabPaD @lgg Thanks for the reports. I was able to reproduce this on my VM. Seems like `system("pause");` is not working for some reason :-/

**Comment by lgg** [comment] 2018-12-05 23:43
@trevj just tried to install `windows-v1.2.21` from scratch. Everything works fine! 
So this issue is fixed with #423

**Comment by daddy2000** [comment] 2018-12-06 02:54
@trevj @lgg Thanks for everyone‘s help。Everything works fine on 1.2.21~

**Comment by trevj** [comment] 2018-12-06 13:45
Great news, thanks everyone for working with me on this and apologies again for the breakage.

**Closed by trevj** 2018-12-06 13:45 UTC
Labels: bug, prioritised

**Comment by TabPaD** [comment] 2018-12-07 09:56
Just installed `windows-v1.2.21` and it works fine. Thanks @trevj
