### ISSUE TITLE
Can't disconnect Outline from IOS settings

### ISSUE THREAD

**Issue by apeTim** [Jigsaw-Code/outline-client#1755] opened 2023-10-18 16:41 UTC
**Describe the bug**
When you disconnect Outline VPN from settings it disconnects but 2 seconds later it automatically reconnects. Many users disconnect VPNs from their settings, but Outline seems to have bug with it. Maybe Outline App thinks that this disconnect was not intentional and tries to reconnect.

**To reproduce**
1. Connect to Outline server
2. Go to settings
3. Go to VPN
4. Press Disconnect

**Expected behavior**
VPN should be disconnected

**Screenshots**
![image](https://github.com/Jigsaw-Code/outline-client/assets/88082374/8c913ef5-584d-4e19-9406-42ef8229aa17)

**Client system (please complete the following information):**
 - Outline Client Version: 1.11.0
 - Your Operating System: IOS16.3.1

**Comment by maddyhof** [comment] 2023-10-23 20:05
Thanks for reaching out. Closing this as a duplicate of #1444.

**Closed by maddyhof** 2023-10-23 20:05 UTC
Labels: bug
