### ISSUE TITLE
cannot rename TAP device to outline-tap0, and need for administrator permissions

### ISSUE THREAD

**Issue by summerdaydream** [Jigsaw-Code/outline-client#696] opened 2019-10-31 17:23 UTC
I failed to install Outline Client on every version after 1.1.2, when it began to use TAP device instead of a global proxy in Windows 10. The reason seemed to be simple: the installer cannot rename the install TAP device ("Ethernet 5, 6, 7...") to "outline-tap0", due to a duplicated name existed on my PC or network. This issue caused an error message in installation saying that the TAP device cannot be installed on my PC, as long time ago it failed to install or rename with non-lartin names.
    
  The problem is that there was not a TAP device with this name. I've tried out every method I can find on Internet, here or at other place. I've checked the registry with "outline-tap0" and the GUIDs to find out any possible conflicting names, but there was none. Manually editing and running add_tap_device.bat managed to create TAP devices with any name ("outline-tap1,2,3...") but still failed to create, rename or configure an existing "ouline-tap0" device. Same error as the netsh set interface name cmd ran.
    
  Funny thing is that, I managed to "rename" the wrongly installed TAP device in registry key \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Network\{4D36E972-E325-11CE-BFC1-08002BE10318}\[InstalledNetAdapterGUID]\name to "outline-tap0", so that the device was displayed as "outline-tap0" in Control Panel (ncpa.cpl), but only displayed---when checking NetConnnectionID by netsh interface show interface, the ID was still "Ethernet x", not "outline-tap0". Looks like the name was a ghost in my PC.

  Things went wired when I found that, desipte the name was only displayed as "outline-tap0", this TAP device actually could work normally. Igoring the error message in installation, and running the client, it told that it needed administrator permissions to run (sure thing I ran it with admin permission), and the status showed that the client did not connect to the server. However, I could use it by setting the proxy server to 127.0.0.1:1081 in Chrome, which was the listening address:port for the client before 1.1.2 version. It worked pretty well. During its try to connect, I noticed that the TAP device status changed (from "net cable unplugged" to "identifying"), but I didnt even configure its gateway/dns/subnet mask (the key values were all lack in regirstry, neither did I use netsh to set them). However, if I click the connect again, the connection lost, and the device status dropped to cable unplugged again. Also, the client could not exit normally, but continuously try to connect. I had to kill its process each time.

  I even tried to build the client from source could myself. The electron.exe told me that the failed permission request happend when it tried to (re)install the route table.

  In summary I guess there were 2 bugs here: a ghost name "outline-tap0" in my PC, and a failed admin permission request. As I read out the issues here without finding a similar one, and old version 1.1.2 client is still working fine, I don't quite expect a quick fix on these bug. Somehow they could just be the problems somewhere in my PC, because the new client can install and work normally in my testing VMware virtual win10 system, with same COMODO anti-virus software. But I am still looking forward to a possible fix, or maybe an alternative option in the client to change its corresponding TAP device name something else than "outline-tap0" so that it could run normally. I still worrying about the algorithm evolution of shadowsocks or the change of server protocol so that ver. 1.1.2 will no longer available in future.

**Comment by ymn** [comment] 2020-03-18 17:09
I am having exactly the same issue. It seems like i also have a ghost "outline-tap0" but i am not able to find and delete it. Even though i found the GUID for outline-tap0 in regedit and deleted it there it still says that i can not rename existing taps with default naming to "outline-tap0" because it aldready exists.

**Comment by summerdaydream** [comment] 2020-04-21 12:18
> I am having exactly the same issue. It seems like i also have a ghost "outline-tap0" but i am not able to find and delete it. Even though i found the GUID for outline-tap0 in regedit and deleted it there it still says that i can not rename existing taps with default naming to "outline-tap0" because it aldready exists.

Kind of comfort to know I'm not the only one to suffer from this lol.  I've been using ver 1.1.2 till now for a passable solution. Actually ver 1.1.2 provides an unexpected advantage that I can manually shut down system proxy in Windows, so that only in chromium browsers with switchyomega extension the traffic goes through outline client, and Windows system updates and other apps go bypass.
Yet, I found encryption algorithm of ver 1.1.2 may have been identified by GFW. Connection to a specific DigitalOcean server will be interfered as long as I go YTB and see some sensitive information. I have to destroy the original droplet and create a new one to reconnect (to change the server ip address). 
My best guess is that, though GFW cannot actually know what the encrypted data is in your traffic, machine learning algorithm may make it possible to detect that the data is going to the forbidden websites.
I am really bothered because without compatibility to update Outline client, I cannot utilize novel encryption to avoid GFW detection. But to be honest I like the proxy method provided by 1.1.2, rather than a global VPN-like tap device adapter.

**Comment by den4ess** [comment] 2023-05-23 14:07
Same issue

**Comment by maddyhof** [comment] 2023-05-30 15:37
Closing as duplicate feature request of #1007

**Closed by maddyhof** 2023-05-30 15:37 UTC

**Comment by yeqwer** [comment] 2025-04-07 11:17
> [#1007](https://github.com/Jigsaw-Code/outline-apps/issues/1007)

I have the exact same problem and it's not a duplicate of #1007. 
I can't rename and can't delete “outline-tap0” either.
