### ISSUE TITLE
Support white list

### ISSUE THREAD

**Issue by qutang** [Jigsaw-Code/outline-client#731] opened 2019-09-09 22:39 UTC
It would be nice if Outline can support white list when directing incoming traffic. This probably can be done by user on the client side with a default white list managed by server administrator.

URLs/IPs on the white list will be connected directly from the client bypassing the VPN server.

This is useful because sometimes we have to switch VPN on and off in order to visit different websites.

**Comment by joeysino** [comment] 2020-01-29 08:59
We had a go at this. Here is a patch, which you are welcome to use as you wish.

We found we had to set a whitelist for Android, and a blacklist for iOS (which we did from outside the plugin). We didn't try to support any other platforms.

<details>

```patch
diff -r ./plugins/cordova-plugin-outline/android/java/org/outline/OutlinePlugin.java /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/android/java/org/outline/OutlinePlugin.java
27a28
> import java.util.ArrayList;
32a34
> import java.util.List;
50a53
>     SET_IP_WHITELIST("setIPWhitelist"),
132c135
<       new HashSet<String>(Arrays.asList(Action.START.value, Action.STOP.value,
---
>       new HashSet<String>(Arrays.asList(Action.SET_IP_WHITELIST.value, Action.START.value, Action.STOP.value,
138a142
>   private List<String> ipWhitelist = null;
159a164
>     broadcastFilter.addAction(Action.SET_IP_WHITELIST.value);
217c222,230
<                   if (Action.START.is(action)) {
---
>                   if (Action.SET_IP_WHITELIST.is(action)) {
>                     //LOG.debug("[OutlinePlugin.java] Received whitelist with length " + args.getJSONArray(1).length() + "");
>                     JSONArray jsonWhitelist = args.getJSONArray(1);
>                     ArrayList<String> _ipWhitelist = new ArrayList<String>();
>                     for (int i = 0; i < jsonWhitelist.length(); i++) {
>                       _ipWhitelist.add(jsonWhitelist.getString(i));
>                     }
>                     ipWhitelist = _ipWhitelist;
>                   } else if (Action.START.is(action)) {
309a323
>     vpnTunnelService.setIPWhitelist(ipWhitelist);
diff -r ./plugins/cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnel.java /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnel.java
23a24
> import java.util.List;
55a57
>   private List<String> ipWhitelist = null;
69a72,75
>   public void setIPWhitelist(List<String> _ipWhitelist) {
>     ipWhitelist = _ipWhitelist;
>   }
> 
96c102,103
<       final ArrayList<Subnet> reservedBypassSubnets = getReservedBypassSubnets();
---
>       //final ArrayList<Subnet> reservedBypassSubnets = getReservedBypassSubnets();
>       final ArrayList<Subnet> reservedBypassSubnets = getIPWhitelistSubnets();
97a105
>         LOG.info("Adding whitelist route: " + subnet.address + "/" + subnet.prefix);
199a208,221
>   /* Returns a list of whitelisted IP ranges. */
>   private ArrayList<Subnet> getIPWhitelistSubnets() {
>     final List<String> subnetStrings = ipWhitelist;
>     ArrayList<Subnet> subnets = new ArrayList<>(subnetStrings.size());
>     for (final String subnetString : subnetStrings) {
>       try {
>         subnets.add(Subnet.parse(subnetString));
>       } catch (Exception e) {
>         LOG.warning(String.format(Locale.ROOT, "Failed to parse subnet: %s", subnetString));
>       }
>     }
>     return subnets;
>   }
> 
diff -r ./plugins/cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java
40a41
> import java.util.List;
71a73
>   private List<String> ipWhitelist = null;
132a135,138
>   public void setIPWhitelist(List<String> _ipWhitelist) {
>     ipWhitelist = _ipWhitelist;
>   }
> 
184a191
>       vpnTunnel.setIPWhitelist(ipWhitelist);
diff -r ./plugins/cordova-plugin-outline/apple/src/OutlinePlugin.swift /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/apple/src/OutlinePlugin.swift
23a24,25
>     static let setIPWhitelist = "setIPWhitelist"
>     static let setIPBlacklist = "setIPBlacklist"
62a65,82
>   func setIPWhitelist(_ command: CDVInvokedUrlCommand) {
>     DDLogInfo("[OutlinePlugin.swift] Receiving ipWhitelist")
>     guard let ipWhitelist = command.argument(at: 1) as? [String] else {
>       return sendError("Missing ipWhitelist", callbackId: command.callbackId)
>     }
>     OutlineVpn.shared.setIPWhitelist(ipWhitelist)
>     self.sendSuccess(callbackId: command.callbackId)
>   }
> 
>   func setIPBlacklist(_ command: CDVInvokedUrlCommand) {
>     DDLogInfo("[OutlinePlugin.swift] Receiving ipBlacklist")
>     guard let ipBlacklist = command.argument(at: 1) as? [String] else {
>       return sendError("Missing ipBlacklist", callbackId: command.callbackId)
>     }
>     OutlineVpn.shared.setIPBlacklist(ipBlacklist)
>     self.sendSuccess(callbackId: command.callbackId)
>   }
> 
diff -r ./plugins/cordova-plugin-outline/apple/src/OutlineVpn.swift /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/apple/src/OutlineVpn.swift
33a34,35
>     static let setIPWhitelist = "setIPWhitelist"
>     static let setIPBlacklist = "setIPBlacklist"
45a48,49
>     static let ipWhitelist = "ipWhitelist"
>     static let ipBlacklist = "ipBlacklist"
88a93,120
>   func setIPWhitelist(_ ipWhitelist: [String]) {
>     DDLogInfo("[OutlineVpn.swift] Receiving ipWhitelist")
>     // Pass the list to PacketTunnelProvider
>     let message = [MessageKey.action: Action.setIPWhitelist,
>                    MessageKey.ipWhitelist: ipWhitelist] as [String : Any]
>     sendVpnExtensionMessage(message) { response in
>       guard response == nil else {
>         DDLogInfo("[OutlineVpn.swift] Problem passing ipWhitelist: \(String(describing: response))")
>         return
>       }
>       DDLogInfo("[OutlineVpn.swift] Successfully passed ipWhitelist")
>     }
>   }
> 
>   func setIPBlacklist(_ ipBlacklist: [String]) {
>     DDLogInfo("[OutlineVpn.swift] Receiving ipBlacklist")
>     // Pass the list to PacketTunnelProvider
>     let message = [MessageKey.action: Action.setIPBlacklist,
>                    MessageKey.ipBlacklist: ipBlacklist] as [String : Any]
>     sendVpnExtensionMessage(message) { response in
>       guard response == nil else {
>         DDLogInfo("[OutlineVpn.swift] Problem passing ipBlacklist: \(String(describing: response))")
>         return
>       }
>       DDLogInfo("[OutlineVpn.swift] Successfully passed ipBlacklist")
>     }
>   }
> 
diff -r ./plugins/cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m
33a34,35
> NSString *const kActionSetIPWhitelist = @"setIPWhitelist";
> NSString *const kActionSetIPBlacklist = @"setIPBlacklist";
38a41,42
> NSString *const kMessageKeyIPWhitelist = @"ipWhitelist";
> NSString *const kMessageKeyIPBlacklist = @"ipBlacklist";
43a48,49
> static NSArray *ipWhitelist;
> static NSArray *ipBlacklist;
252a259,268
>   } else if ([kActionSetIPWhitelist isEqualToString:action]) {
>     DDLogInfo(@"[PacketTunnelProvider.m] receiving ipWhitelist");
>     NSArray *ipWhitelistIn = message[kMessageKeyIPWhitelist];
>     ipWhitelist = ipWhitelistIn;
>     completionHandler(nil);
>   } else if ([kActionSetIPBlacklist isEqualToString:action]) {
>     DDLogInfo(@"[PacketTunnelProvider.m] receiving ipBlacklist");
>     NSArray *ipBlacklistIn = message[kMessageKeyIPBlacklist];
>     ipBlacklist = ipBlacklistIn;
>     completionHandler(nil);
314a331,336
>   // Original code:
>   //ipv4Settings.includedRoutes = @[[NEIPv4Route defaultRoute]];
>   //ipv4Settings.excludedRoutes = [self getExcludedIpv4Routes];
>   // Our modifications:
>   // No matter what we set for includedRoutes, it seems to include every address which is not excluded!
>   // Therefore we include everything, but exclude addresses we don't want.
316c338
<   ipv4Settings.excludedRoutes = [self getExcludedIpv4Routes];
---
>   ipv4Settings.excludedRoutes = [self getBlacklistedIpv4Routes];
336a359
>   DDLogInfo(@"[PacketTunnelProvider.m] Getting excluded routes");
338,340c361
<     NEIPv4Route *route =
<         [[NEIPv4Route alloc] initWithDestinationAddress:subnet.address subnetMask:subnet.mask];
<     [excludedIpv4Routes addObject:route];
---
>     [excludedIpv4Routes addObject:[self getRouteFromSubnet:subnet]];
344a366,389
> - (NSArray *)getWhitelistedIpv4Routes {
>   NSMutableArray *whitelistedRoutes = [[NSMutableArray alloc] init];
>   DDLogInfo(@"[PacketTunnelProvider.m] Getting whitelisted routes");
>   for (Subnet *subnet in [Subnet buildSubnetsList:ipWhitelist]) {
>     [whitelistedRoutes addObject:[self getRouteFromSubnet:subnet]];
>   }
>   return whitelistedRoutes;
> }
> 
> - (NSArray *)getBlacklistedIpv4Routes {
>   NSMutableArray *blacklistedRoutes = [[NSMutableArray alloc] init];
>   DDLogInfo(@"[PacketTunnelProvider.m] Getting blacklisted routes");
>   for (Subnet *subnet in [Subnet buildSubnetsList:ipBlacklist]) {
>     [blacklistedRoutes addObject:[self getRouteFromSubnet:subnet]];
>   }
>   return blacklistedRoutes;
> }
> 
> - (NEIPv4Route *)getRouteFromSubnet:(Subnet *)subnet {
>   NEIPv4Route *route =
>       [[NEIPv4Route alloc] initWithDestinationAddress:subnet.address subnetMask:subnet.mask];
>   return route;
> }
> 
diff -r ./plugins/cordova-plugin-outline/apple/vpn/Subnet.swift /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/apple/vpn/Subnet.swift
62a63,72
>   static func buildSubnetsList(_ stringArray: NSArray) -> [Subnet] {
>     var subnets: [Subnet] = []
>     for cidrSubnet in stringArray {
>       if let subnet = self.parse(cidrSubnet as! NSString as String) {
>         subnets.append(subnet)
>       }
>     }
>     return subnets
>   }
> 
diff -r ./plugins/cordova-plugin-outline/outlinePlugin.js /home/joey/outline-client-with-whitelists/plugins/cordova-plugin-outline/outlinePlugin.js
99a100,109
> // Not used on iOS
> Connection.prototype.setIPWhitelist = function(whitelist) {
>   return this._promiseExec('setIPWhitelist', [whitelist]);
> };
> 
> // Only used on iOS
> Connection.prototype.setIPBlacklist = function(blacklist) {
>   return this._promiseExec('setIPBlacklist', [blacklist]);
> };
> 
```

</details>

Related (possibly): #556 #624 #582

**Comment by joeysino** [comment] 2020-01-30 03:18
Here is a pull request for the above patch: https://github.com/Jigsaw-Code/outline-client/compare/master...joeysino:ip-whitelist?expand=1

**Comment by JonathanDCohen** [comment] 2020-01-31 20:28
My .02, we've talked about selective proxying features like this.  We probably want to think about what we want UX to be for something like this.

**Comment by ShadyRover** [comment] 2022-03-29 17:24
Need help?

**Comment by RuBAN-GT** [comment] 2023-09-29 08:16
Any updates?

**Comment by maddyhof** [comment] 2023-10-16 17:44
Closing as duplicate of #887

**Closed by maddyhof** 2023-10-16 17:44 UTC
Labels: feature request
