### ISSUE TITLE
No data in dropdown

### ISSUE THREAD

**Issue by d1eselboy** [Jigsaw-Code/outline-client#126] opened 2018-06-04 13:55 UTC
Hello!
There is no data in Outline 1.1.0. Older versions worked properly.
OS X EL Capitan:
![screen shot 2018-06-04 at 16 55 13](https://user-images.githubusercontent.com/4608856/40921429-15fb983c-6818-11e8-8249-4b1833639613.png)

Outline Screenshot:
![screen shot 2018-06-04 at 16 52 51](https://user-images.githubusercontent.com/4608856/40921323-cf8e5358-6817-11e8-8ace-883dac80328f.png)

**Comment by d1eselboy** [comment] 2018-06-04 14:03
Can i download previous version of Outline somewhere? 
Or start it up via CLI?

**Comment by rafaelluna** [comment] 2018-06-05 03:05
Same problem here.
OSX 10.11.6

**Comment by VadimCpp** [comment] 2018-06-10 12:41
When it is going to be fixed? Is there a plan for future release?

**Comment by fortuna** [comment] 2018-06-12 18:32
Duplicate of #93. Please follow the issue there.

This has been fixed in 1.1.1, but hasn't been released on the App Store yet.

**Closed by fortuna** 2018-06-12 18:32 UTC
