### ISSUE TITLE
GUI shows no errors but logs have DNS and launcher errors

### ISSUE THREAD

**Issue by mjgs** [Jigsaw-Code/outline-client#433] opened 2018-12-11 11:34 UTC
According to the GUI the client is connected without errors, and the internet connection is working, I can browse the web etc. However when I look in the logs there are a bunch of errors:

A lot of these:

```
VpnExtension[59669]: Failed to retrieve mapping for DNS request ID 60948
```

and then this error which never stops:

```
Dec 11 17:52:36 MarksComputer com.apple.xpc.launchd[1] (org.outline.macos.client.launcher[61611]): Could not find and/or execute program specified by service: 45: Operation not supported: org.outline.macos.client.launcher
Dec 11 17:52:36 MarksComputer com.apple.xpc.launchd[1] (org.outline.macos.client.launcher): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

Why are there errors in the logs yet no errors in the GUI?
Why is the outline mac client launcher respawning the whole time? 
Is the VPN actually connected, or is the internet traffic actually from the non vpn connection?

**Comment by trevj** [comment] 2018-12-11 12:40
@mjgs Do you have a specific issue to report?

**Comment by trevj** [comment] 2018-12-13 15:41
@mjgs Some errors do not warrant mention in the UI; some errors are spurious. @alalamav addressed the mapping error recently:
https://github.com/Jigsaw-Code/outline-client/issues/407#issuecomment-445297536

I'm sure you'll find a lot of unnecessary log messages across all our platforms. Chasing them all down would be a never-ending task - we happily accept pull requests.

@alalamav Do you know anything about the second error message, above?

**Comment by alalamav** [comment] 2018-12-13 18:13
I haven't seen it in my devices. @mjgs, we register a small binary, `org.outline.macos.client.launcher`, to start on login. It is responsible for starting Outline on boot if the VPN was connected at shutdown. Try running `launchctl remove org.outline.macos.client.launcher` and restarting the app.

**Comment by alalamav** [comment] 2018-12-14 16:58
The command unregisters the Outline launcher program from your login items. It should not have any effects on the VPN connection. When you restart the app, it will be registered again.

**Comment by mjgs** [comment] 2018-12-20 12:48
@alalamav I ran the command, it completed without error, then I selected Quit in the client menu, then reconnected the VPN, and the launcher errors are still being written to the logs. The launcher errors are written to the logs both when the client is connected and when it is not connected VPN. Is there some other way I should have ran the command?

**Comment by trevj** [comment] 2018-12-20 15:35
@mjgs Which version of macOS are you running?

**Comment by mjgs** [comment] 2018-12-21 04:39
@trevj El Capitan

**Comment by trevj** [comment] 2019-01-15 18:21
Not sure what the problem is here, closing this issue.

**Closed by trevj** 2019-01-15 18:21 UTC
Labels: need more info

**Comment by mjgs** [comment] 2019-01-16 04:17
@trevj Is there some other info I could give you to help troubleshoot? I'm getting thousands and thousands of these messages per day filling up system logs. The message is saying that the binary is not there, where should it be?
