### ISSUE TITLE
How to get data usage of a connection instead of a access_key

### ISSUE THREAD

**Issue by ChenforCode** [Jigsaw-Code/outline-client#1296] opened 2022-05-05 09:02 UTC
I want to record the data usage of a connection. I just need data or interface, because currently I can only get the data usage of access_key in outline manager, but one access_key may be used by more than one person, so I would like to ask if I can get the usage of one user, or the data usage of one connection (one user's connection through access_key).

**Comment by bemasc** [comment] 2022-05-05 14:31
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/1094

**Closed by bemasc** 2022-05-05 14:31 UTC
