### ISSUE TITLE
Hi @simakazi, thanks for reporting the issue. From the logs I can see:

### ISSUE THREAD

**Issue by PhoeKhwar12** [Jigsaw-Code/outline-client#1572] opened 2023-02-11 05:16 UTC
Hi @simakazi, thanks for reporting the issue. From the logs I can see:

```
OutlineProxyController[8974]: updated unix socket owner to 4294967295,1002
```

This means we failed to get the current user's uid (the first number `4294967295` which is equivalent to `-1`) and grant the required permissions to `rw` `/var/run/outline_controller`. This needs further investigation (for example, maybe the uid has been changed). As a workaround, could you try adding your current user to the `outlinevpn` group (we should already created this group) and restart the machine?

```
usermod -aG outlinevpn "$USER"
```

_Originally posted by @jyyi1 in https://github.com/Jigsaw-Code/outline-client/issues/1526#issuecomment-1370365189_

**Comment by PhoeKhwar12** [comment] 2023-02-11 05:17
[Uploading outline-0.67.2 2.zip…]()

**Comment by maddyhof** [comment] 2023-02-13 15:49
Closing as duplicate of #1526

**Closed by maddyhof** 2023-02-13 15:49 UTC
Labels: duplicate
