### ISSUE TITLE
AppImage crashes with segmentation fault

### ISSUE THREAD

**Issue by nhand64** [Jigsaw-Code/outline-client#746] opened 2020-02-18 12:37 UTC
**Describe the bug**
Hi, I have recently met this issue when trying to run the client's AppImage on my computer. Whenever it launches, it crashes and throwing an error

`[1]    <process id> segmentation fault (core dumped)`

**To Reproduce**
Whenever launch it with files manager or terminal, it still crashes.

**Expected behavior**
I just expected it to launch and work normally.

**Screenshots**
It crashes and left nothing to capture.

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed

**Additional context**
Note: I don't know why this issue happens only with me, other people with the same distro with me still using it normally. The manager one still working fine for me.

**Comment by JonathanDCohen** [comment] 2020-02-20 18:06
Hey there, sorry you're running into this issue.  Did you build the client yourself or is it our production binary?  Have you tried building yourself and seeing if it works?

**Comment by Wello6143** [comment] 2020-02-21 00:48
I tried both latest version and pre-release of binary. I don't have much time to build it myself but I will try to do so and report as sooon as possible.

**Comment by JonathanDCohen** [comment] 2020-02-21 17:37
Interesting, sorry this has been an issue.  Shooting in the dark, do you know what libc and POSIX toolset you're using?  I did a few quick Google searches to see what could cause a segfault from an electron app and a few people reported some issues with their glibc versions being the culprit (https://github.com/electron/electron/issues/13972 for example)

**Comment by Wello6143** [comment] 2020-02-22 09:30
I searched about how electron struggle up with `glibc` and yes, my distro has the latest version of `glibc` 2.31 so things struggled up right here

**Comment by Wello6143** [comment] 2020-02-22 15:05
So far I can't force my package manager to downgrade `glibc`, also `dmesg` printed these two lines:
```
[ +20.048764] outline-client[10366]: segfault at 0 ip 000055961701e754 sp 00007fff686641a0 error 4 in outline-client[559614e3b000+53ac000]
[  +0.000007] Code: 41 54 53 48 83 ec 48 49 89 f7 49 89 fe 48 8d 35 ea 12 69 fd 48 8d 7d c0 e8 39 cf d5 ff bf 70 00 00 00 e8 2f a7 db ff 49 89 c4 <41> 8b 06 89 45 d4 41 c7 06 00 00 00 00 4c 8b 6d c0 4d 85 ed 74 06
```
And sorry, POSIX is a new thing to me then.

**Comment by gloomy-ghost** [comment] 2020-12-30 07:06
interestingly, I saw the initialisation UI at first launch as the terminal output indicates the program is checking update and generating uid, then it crashed with segfault. Further attempts always crash instantly even if I clear the `~/.config/Outline Manager/` directory. Are there some config data store in somewhere else?

**Comment by Wello6143** [comment] 2021-01-09 09:43
Considering all distros are working fine with the client, I'm going to close this issue, feel free to reopen this if the issue is still happening on your system!

**Comment by alonek1** [comment] 2021-01-31 12:12
I have same problem on ubuntu 2020.04

**Comment by maddyhof** [comment] 2023-04-25 20:12
@alonek1 is this still occurring on the latest version of the Outline Client?

**Closed** 2023-05-22 14:43 UTC
Labels: bug, need more info, os/linux, failure/start
