### ISSUE TITLE
Add client for Linux (AppImage would be best)

### ISSUE THREAD

**Issue by keeganjk** [Jigsaw-Code/outline-client#84] opened 2018-05-06 22:04 UTC
Please add support for a Linux client. I just dual-booted my laptop with Linux and it would be nice to be able to run it on Linux.

I would reccommend using .AppImage ([](https://appimage.org/)), which allows a program that can be run on any platform simply by making it executable and running it (FUSE also needs to be installed which is on most platforms and easy to install otherwise).

**Comment by bemasc** [comment] 2018-05-07 14:17
Duplicate of #10.

The Outline Manager uses AppImage on Linux, so it's reasonable to imagine that a version of the Outline Client for Linux might be built the same way.

**Closed by bemasc** 2018-05-07 14:17 UTC
Labels: duplicate
