### ISSUE TITLE
per-app selective proxying

### ISSUE THREAD

**Issue by ElementMTT** [Jigsaw-Code/outline-client#180] opened 2018-07-20 07:21 UTC
Thank you to the Jigsaw team.
I hope that the subsequent version can add the "Per-app proxy" function, because in China or Iran, the Outline, all services (App) that need to be connected through the Outline, resulting in some services will become very slow (wechat \ weibo \ alipay) Can you add a feature that only passes a proxy for an APP? thank

**Comment by studentmain** [comment] 2018-07-20 15:40
If you really need now, use shadowsocks-windows, it has a "PAC mode".

ElementMTT <notifications@github.com> 于 2018年7月20日周五 15:21写道：

**Comment by trevj** [comment] 2018-07-24 21:34
@ElementMTT Thanks for the suggestion!

**Comment by sandrigo** [comment] 2018-07-26 21:20
Related: https://github.com/Jigsaw-Code/outline-client/issues/88

**Comment by moralrebuild** [comment] 2018-12-13 05:48
This is a killer feature. Please hear users' voice and roll out as quick as possible. Currently some closed-source apps in iOS already provides similar 'smart routing' functionality, but from my point of view, outline obviously serves as a much stable and reliable choice.  You know those apps were developed and maintained by unknown developers who not only throw tons of ads in the apps but also potentially steal personal information and sale / transfer it to China, Iran and North Korea government.

**Comment by sandrigo** [comment] 2018-12-13 15:18
Hi @moralrebuild -- we hear loud and clear :) 
Do you have an example of an iOS app that does this?

**Comment by cjhenck** [comment] 2019-05-20 17:03
Zero-rated services are another reason to want this. E.g. certain messenger/carrier combinations.

**Comment by dban0001** [comment] 2019-11-13 21:54
Most "normal" VPN apps allow this. It would be very nice to have.

**Comment by recolic** [comment] 2021-07-06 07:49
An example does this: https://github.com/shadowsocks/shadowsocks-android

**Comment by fortuna** [comment] 2021-08-17 22:52
Duplicate of https://github.com/Jigsaw-Code/outline-client/issues/887

**Closed by fortuna** 2021-08-17 22:52 UTC
Labels: feature request, prioritised
