### ISSUE TITLE
can not install client on windows 10

### ISSUE THREAD

**Issue by HongyanR** [Jigsaw-Code/outline-client#524] opened 2019-02-12 06:48 UTC
![image](https://user-images.githubusercontent.com/26659344/52616942-2da1c900-2ed5-11e9-9738-668662ebc9d7.png)

**Comment by trevj** [comment] 2019-03-05 19:07
@HongyanR Thanks for trying Outline. Apologies for the delay in getting back to you. Can you please provide some of the information requested by the "Bug report" issue template?:
https://github.com/Jigsaw-Code/outline-client/issues/new?assignees=&labels=&template=bug_report.md&title=

Additionally, for this issue in particular, can you please paste the output of this command:
```
wmic nic get index,interfaceindex,name,netconnectionid,servicename,configmanagererrorcode,netconnectionstatus
```

Thanks!

**Comment by fastom800** [comment] 2019-03-29 20:35
Hi, I have the same issue. I had already installed Outline, and it was working fine. Yesterday I also installed OpenVPN. Now, when I connect with client, it says that program installed incorrectly. Now I try to reinstall it, and see this error. Even so Outline can be launched, but it doesn't connect to the server.
```
wmic nic get index,interfaceindex,name,netconnectionid,servicename,configmanagererrorcode,netconnectionstatus
ConfigManagerErrorCode  Index  InterfaceIndex  Name                                       NetConnectionID                                  NetConnectionStatus  ServiceName
0                       0      17              WAN Miniport (SSTP)                                                                                              RasSstp
0                       1      19              Microsoft Kernel Debug Network Adapter                                                                           kdnic
0                       2      11              Intel(R) Dual Band Wireless-AC 8265        Беспроводная сеть                2                    Netwtw06
0                       3      6               Bluetooth Device (Personal Area Network)   Сетевое подключение Bluetooth  7                    BthPan
0                       4      21              Microsoft Wi-Fi Direct Virtual Adapter                                                                           vwifimp
0                       5      5               WAN Miniport (IKEv2)                                                                                             RasAgileVpn
0                       6      16              WAN Miniport (L2TP)                                                                                              Rasl2tp
0                       7      8               WAN Miniport (PPTP)                                                                                              PptpMiniport
0                       8      14              WAN Miniport (PPPOE)                                                                                             RasPppoe
0                       9      15              WAN Miniport (IP)                                                                                                NdisWan
0                       10     12              WAN Miniport (IPv6)                                                                                              NdisWan
0                       11     9               WAN Miniport (Network Monitor)                                                                                   NdisWan
0                       12     18              Microsoft Wi-Fi Direct Virtual Adapter #2                                                                        vwifimp
0                       13     10              TAP-Windows Adapter V9 #2                  Ethernet                                         7                    tap0901
0                       14     3               TAP-Windows Adapter V9 #3                  Ethernet 2                                       7                    tap0901
```

**Comment by xuanyaunlei1020** [comment] 2019-08-07 14:52
I tried several laptops of windows 10 ( about 8 laptops), but a few of them (3 of them) always show this error. In my opinion, it might is the tap-windows-driver problem( tips: https://www.thewindowsclub.com/tap-windows-adapters-vpn-driver). I tried to solve this problem by update tap-windows-driver, but it did not work. Hope my comments may help you.


Before install outline, the Network adapters shows as below:
![image](https://user-images.githubusercontent.com/13135707/62632363-f3d1ec80-b964-11e9-9223-a86362a80802.png)
After install outline, the Network adapters shows as below:
 
![image](https://user-images.githubusercontent.com/13135707/62632746-912d2080-b965-11e9-905f-be0f607c5e73.png)



The error as below:
![image](https://user-images.githubusercontent.com/13135707/62632559-44494a00-b965-11e9-8b66-a03353e8afa0.png)

The version of outline is :1.2.33.0
![image](https://user-images.githubusercontent.com/13135707/62632490-20860400-b965-11e9-9b2b-601a02e46729.png)

**Comment by xuanyaunlei1020** [comment] 2019-08-07 15:13
The output you might need.
```
C:\Users\Administrator>wmic nic get index,interfaceindex,name,netconnectionid,servicename,configmanagererrorcode,netconnectionstatus
ConfigManagerErrorCode  Index  InterfaceIndex  Name                                       NetConnectionID  NetConnectionStatus  ServiceName
0                       0      6               Microsoft Kernel Debug Network Adapter                                           kdnic
0                       1      19              Intel(R) Wireless-AC 9462                  WLAN             2                    Netwtw08
0                       2      7               Realtek PCIe GbE Family Controller         以太网           7                    rt640x64
0                       3      8               WAN Miniport (SSTP)                                                              RasSstp
0                       4      16              WAN Miniport (IKEv2)                                                             RasAgileVpn
0                       5      18              WAN Miniport (L2TP)                                                              Rasl2tp
0                       6      15              WAN Miniport (PPTP)                                                              PptpMiniport
0                       7      3               WAN Miniport (PPPOE)                                                             RasPppoe
0                       8      4               WAN Miniport (IP)                                                                NdisWan
0                       9      13              WAN Miniport (IPv6)                                                              NdisWan
0                       10     11              WAN Miniport (Network Monitor)                                                   NdisWan
0                       11     14              Bluetooth Device (Personal Area Network)   蓝牙网络连接     7                    BthPan
0                       12     17              Microsoft Wi-Fi Direct Virtual Adapter                                           vwifimp
0                       13     9               Microsoft Wi-Fi Direct Virtual Adapter #2                                        vwifimp
```

** Additional info** : shadowsocks  and outline manager works wellThe output you might need.
```
C:\Users\Administrator>wmic nic get index,interfaceindex,name,netconnectionid,servicename,configmanagererrorcode,netconnectionstatus
ConfigManagerErrorCode  Index  InterfaceIndex  Name                                       NetConnectionID  NetConnectionStatus  ServiceName
0                       0      6               Microsoft Kernel Debug Network Adapter                                           kdnic
0                       1      19              Intel(R) Wireless-AC 9462                  WLAN             2                    Netwtw08
0                       2      7               Realtek PCIe GbE Family Controller         以太网           7                    rt640x64
0                       3      8               WAN Miniport (SSTP)                                                              RasSstp
0                       4      16              WAN Miniport (IKEv2)                                                             RasAgileVpn
0                       5      18              WAN Miniport (L2TP)                                                              Rasl2tp
0                       6      15              WAN Miniport (PPTP)                                                              PptpMiniport
0                       7      3               WAN Miniport (PPPOE)                                                             RasPppoe
0                       8      4               WAN Miniport (IP)                                                                NdisWan
0                       9      13              WAN Miniport (IPv6)                                                              NdisWan
0                       10     11              WAN Miniport (Network Monitor)                                                   NdisWan
0                       11     14              Bluetooth Device (Personal Area Network)   蓝牙网络连接     7                    BthPan
0                       12     17              Microsoft Wi-Fi Direct Virtual Adapter                                           vwifimp
0                       13     9               Microsoft Wi-Fi Direct Virtual Adapter #2                                        vwifimp
```

** Additional info** : shadowsocks  and outline manager works well

**Comment by xuanyaunlei1020** [comment] 2019-08-07 15:59
after a  few investagtion, i think below files might help us to find the reason. links: https://community.openvpn.net/openvpn/wiki/ManagingWindowsTAPDrivers
> You can further debug tap-windows installation issues by looking at the common log file for all Windows driver installations, which on Windows 7 is normally located in C:\Windows\inf\setupapi.dev.log. If you're filing a bug report, you should attach the logs for the tap-windows installation part to the bug report.

[setupapi.dev.log](https://github.com/Jigsaw-Code/outline-client/files/3477878/setupapi.dev.log)

**Comment by xuanyaunlei1020** [comment] 2019-08-07 16:48
after unzip outline-client, and try use the batch file, it turns out:

![image](https://user-images.githubusercontent.com/13135707/62641407-0ef92800-b976-11e9-943c-17163ecab610.png)

**Comment by alalamav** [comment] 2019-08-07 17:46
Hi @xuanyaunlei1020, thanks for diving deep into this issue. I have a few questions:

* Did the 3 laptopts that fail to install Outline have the TAP device (OpenVPN) installed?
* I don't see any TAP device install failures in `setupapi.dev.log`, do you happen to have the output of the installations that failed?
* Did you run the `add_tap_device.bat` script as admin?

**Comment by xuanyaunlei1020** [comment] 2019-08-08 02:13
> * Did the 3 laptopts that fail to install Outline have the TAP device (OpenVPN) installed?
At least my laptop did not install any TAP device(OpenVPN), only installed the shadowsocks. Other 2 are my co-workers' , I am not clear about them.

> * I don't see any TAP device install failures in `setupapi.dev.log`, do you happen to have the output of the installations that failed?
Oh, I have on idea about this `setupapi.dev.log`, I think this file may help us. But this file do have some access error. Do these error show any hint to us?

> * Did you run the `add_tap_device.bat` script as admin?
Yes.

**Comment by trdat** [comment] 2019-11-22 18:11
try change Compability in Properties of Outline-Client.exe to Windows 7. It works for me!

**Comment by CrazyTeaFs** [comment] 2019-12-14 09:13
Same error... TAP device could not installed....

**Comment by jsyoo3722** [comment] 2019-12-15 03:34
What is going on with this issue?
I'm having the exactly same issue on some laptops.

The installation throws the same pop-up message, while it does install the TAP driver.
However, the installed outline app fails to connect.

I have never had this issue using older versions.
I'm not so sure why this started happening.

Is there any workaround for this?

**Comment by ComputerPark** [comment] 2019-12-19 12:59
I had the exact same issue on Outline Client 1.3.1 !
However, when I tried using Outline 1.2.27, it worked flawlessly.

It seems something's wrong with the new versions...

**Comment by ilinbxu** [comment] 2019-12-20 08:17
I had the exact same issue on Outline Client 1.3.1 !

**Comment by NoPlayer40600** [comment] 2020-01-03 11:56
> @ComputerPark 
> 
> I had the exact same issue on Outline Client 1.3.1 !
> However, when I tried using Outline 1.2.27, it worked flawlessly.
> 
> It seems something's wrong with the new versions...

I agree on his/her suggestion.
My problem was exactly same as @HongyanR .

Installer version was 1.3.1.0, which is the latest version when I wrote this reply.
After installation, Outline is excutable as normally does, able to add server but cannot connect with error message saying TAP device is not installed correctly.
I tried clean Windows 10 installation for 3 times with trial of Outline install, but saying same error message all the time.

As @ComputerPark did, I tried install 1.2.32 and it worked! No error message, fine connection.
After first run, auto-update script updated my Outline program to version 1.3.1.0.
Even on updated version, it worked as intended.

Maybe the latest version containes corrupted TAP driver?

> 1.3.1.0 Direct installation -> Fail
> 1.2.32 Direct installation -> Work
> 1.3.1.0 Update installation (from 1.2.32) -> Work

**Comment by itisng** [comment] 2020-02-15 12:49
It's still not fixed today, but anyway thank you @jsyoo3722, I installed the 1.2.32 and it's fine.

**Comment by c0state** [comment] 2020-02-24 03:50
After the install fails, you should still have a TAP network adapter in your adapters list. Try to rename it to `outline-tap0` and then re-run the installer. That worked for me.

If you get an error stating that `outline-tap0` already exists even though it's nowhere to be found in your device management list (and you've enabled "show hidden devices"), then you might need to follow these instructions to remove the problematic entry that is preventing the rename: https://superuser.com/a/1425141/117114 (Note: I used https://github.com/M2Team/NSudo instead of the tool mentioned in that post to gain "Trusted Installer" privileges).

I was able to get Outline back up and running with these instructions. To be fair this is a Windows issue from what I can tell.

**Comment by pianzuo** [comment] 2020-02-26 08:41
I find a solution. work for me.

1. after failure, delete TAP-Windows Adapter V9 from device manager
2. add chcp 65001 to the first line of  add_tap_device.bat. It seems like this:


![image](https://user-images.githubusercontent.com/13371759/75326918-777a0900-58b6-11ea-9b99-042e1ab78dd0.png)

3. open cmd with admin. 
4. change dir to C:\Program Files (x86)\Outline
5. run add_tap_device.bat. 

done.

**Comment by leiwng** [comment] 2020-03-04 14:37
> I find a solution. work for me.
> 
> 1. after failure, delete TAP-Windows Adapter V9 from device manager
> 2. add chcp 65001 to the first line of  add_tap_device.bat in C:\Program Files (x86)\Outline. It seems like this:
> 
> ![image](https://user-images.githubusercontent.com/13371759/75326918-777a0900-58b6-11ea-9b99-042e1ab78dd0.png)
> 
> 1. open cmd with admin.
> 2. change dir to C:\Program Files (x86)\Outline
> 3. run add_tap_device.bat.
> 
> done.

hey guys, it's works for me, Thanks very much!

**Comment by pianzuo** [comment] 2020-03-04 14:42
You are welcome.

leiwng <notifications@github.com> 于 2020年3月4日周三 22:37写道：

**Comment by immartian** [comment] 2020-03-12 13:38
seems it's not solved yet, any clues?

**Comment by pianzuo** [comment] 2020-03-12 14:36
more detail?

Im <notifications@github.com> 于2020年3月12日周四 下午9:38写道：

**Comment by immartian** [comment] 2020-03-12 15:29
There are still TAP issue with the newest release on Windows 10, not a helpful message with the dialog. 
![image](https://user-images.githubusercontent.com/81030/76537767-3a6a6500-64b9-11ea-8f1e-81baac2eb2f2.png)

**Comment by pianzuo** [comment] 2020-03-12 23:15
you can find me on qq，1088302

Im <notifications@github.com> 于 2020年3月12日周四 23:29写道：

**Comment by immartian** [comment] 2020-03-12 23:44
we don't use QQ(security reason), signal/telegram.

**Comment by WoodpeckerBaby** [comment] 2020-05-04 19:18
Remember, you must install v1.2.x and set the windows Tap driver up connect at least once 
before installing v1.3.x.

 Direct install of 1.3.x will fail either in the installation stage
or during the connection stage. 

Remember to purge both the windows Tab Driver via WIN+X -> device management, and the
AppData folder under C:\Users\----YOUR_USER_NAME----\AppData\Roaming\Outline
I had this issue and this fixed it. Just like others here have testified, the latest TAP driver is corrupt. 

https://github.com/Jigsaw-Code/outline-client/issues/737#issuecomment-623640902 was my experience before I fixed it.

**Comment by fortuna** [comment] 2020-11-10 16:09
A lot has changed and many issues. were fixed since this bug was opened. I'll close it and we can reopen with fresh data if needed.

**Closed by fortuna** 2020-11-10 16:09 UTC
Labels: need more info

**Comment by mecitorta** [comment] 2020-11-29 22:22
i tried to installed v1.2.x but still same :/

**Comment by mecitorta** [comment] 2020-11-29 22:23
> Remember, you must install v1.2.x and set the windows Tap driver up connect at least once
> before installing v1.3.x.
> 
> Direct install of 1.3.x will fail either in the installation stage
> or during the connection stage.
> 
> Remember to purge both the windows Tab Driver via WIN+X -> device management, and the
> AppData folder under C:\Users----YOUR_USER_NAME----\AppData\Roaming\Outline

all of them i tried to fix this problem but still same.
