### ISSUE TITLE
Detected as a Trojan via Windows Defender

### ISSUE THREAD

**Issue by mxschmitt** [Jigsaw-Code/outline-client#51] opened 2018-04-01 10:57 UTC
Details:
![image](https://user-images.githubusercontent.com/17984549/38172403-121ca916-35ac-11e8-9aef-cf1580a51891.png)

**Comment by griffinbai** [comment] 2018-04-01 13:34
I also encountered this warning too .
![default](https://user-images.githubusercontent.com/10183338/38173620-4132f208-35f4-11e8-810f-239a040d5305.JPG)

**Comment by lifeva** [comment] 2018-04-03 03:31
me too

**Comment by suonli** [comment] 2018-04-10 01:56
me too
Trojan:Win32/Bitrep.B

**Comment by trevj** [comment] 2018-04-11 13:16
Related issue:
https://github.com/Jigsaw-Code/outline-client/issues/12

**Comment by trevj** [comment] 2018-04-12 15:44
@mxschmitt, @griffinbai, @lifeva, @suonli - many thanks for the reports. This is really useful for us. I'm going to mark this as a duplicate of https://github.com/Jigsaw-Code/outline-client/issues/12 and continue discussion there.

**Closed by trevj** 2018-04-12 15:44 UTC
Labels: bug
