### ISSUE TITLE
[Bug]: Devices running iOS versions lower than 17 cannot function properly.

### ISSUE THREAD

**Issue by laowant** [Jigsaw-Code/outline-client#2282] opened 2024-11-19 12:36 UTC
### Application

Outline Client

### Describe the bug

Apple devices running iOS 16 or earlier can successfully install the Outline app, but after installation, no areas of the app are touch-responsive. Tapping on any page element produces no reaction. Even when importing via an SS URL format, the interface elements remain completely unresponsive.

### Steps to reproduce

Apple devices running iOS 16 or earlier can successfully install the Outline app, but after installation, no areas of the app are touch-responsive. Tapping on any page element produces no reaction. Even when importing via an SS URL format, the interface elements remain completely unresponsive.

### Outline Version

1.14.0

### What operation system are you using?

iOS

### Operating System Version

iOS16

**Comment by sbruens** [comment] 2024-11-19 20:39
Thanks for providing these details. I can now see this is a dupe of #2276. We'll post updates there.

**Closed as not planned by sbruens** 2024-11-19 20:39 UTC
Labels: bug
