### ISSUE TITLE
UDP not allowed

### ISSUE THREAD

**Issue by Per0x** [Jigsaw-Code/outline-client#412] opened 2018-12-01 23:04 UTC
Outline Client on Windows 10 say that UDP is not allowed on my server and can't connect.
However It works well on my  Android for the same server, from the same network as my PC (works in LTE too). On the server side, ports are open for TCP and UDP.
I only have Windows Defender as firewall on my desktop, and I also tried with windows firewall disable, same result.

**Comment by XiaoFaye** [comment] 2018-12-06 03:06
check here: #426

**Comment by trevj** [comment] 2018-12-06 16:58
@Per0x Thanks for the report. We have received similar reports, e.g. https://github.com/Jigsaw-Code/outline-client/issues/329, but I'm afraid we don't fully understand why only Windows would be affected. However, as @XiaoFaye notes, we have been working to support servers/networks without UDP support which I think will address the issue for you.

**Comment by trevj** [comment] 2018-12-06 16:59
Duplicate of:
https://github.com/Jigsaw-Code/outline-client/issues/329

**Closed by trevj** 2018-12-06 16:59 UTC
Labels: duplicate
