### ISSUE TITLE
Still running as x86 not ARM on M1

### ISSUE THREAD

**Issue by iambenmitchell** [Jigsaw-Code/outline-client#1590] opened 2023-03-03 20:43 UTC
**Describe the bug**
It has been a few years now since M1 has been released and Outline is still running as an Intel x86 App. 

**To Reproduce**
1. Download Outline from the App Store on an M1 Device
2. Notice that the app is running as `Intel` in Activity Monitor

**Expected behavior**
1. Download Outline from the App Store on an M1 Device
2. Notice that the app is running as `Apple` in Activity Monitor

**Screenshots**
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/27426792/222825275-fc996ca3-e533-4ce7-9684-2da6a9057d1c.png">

**Client System (please complete the following information):**
 - Outline Client Version `1.10.0`
 - Your Operating System: `macOS 13.2.1 (22D68)`

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**

**Comment by iambenmitchell** [comment] 2023-03-03 20:45
BTW, this is a duplicate of #940 -- but it seems that was created over 2 years ago and hasn't been fully addressed yet

**Comment by fortuna** [comment] 2023-07-13 21:57
Closing, as it's a duplicate of https://github.com/Jigsaw-Code/outline-client/issues/940

**Closed by fortuna** 2023-07-13 21:57 UTC
Labels: bug
