### ISSUE TITLE
 GNU/Linux AppImage chrome-sandbox Canonical Permissions/Ownerships Issue

### ISSUE THREAD

**Issue by davidganz** [Jigsaw-Code/outline-client#883] opened 2020-10-11 15:43 UTC
Hi!

OS: Kali 2020
Message: You need to make sure that chrome-sandbox is owned by root and has mode 4755.
So the App Client as well as the Manager cannot be Run on GNU/Linux Kali due to the chrome-sandbox ownership issue.
That's because when you are packaging the App with appimagetool the root ownership is automatically changed to the User.
Also see: laurent22/joplin#2246 (comment)
Try find out a Solution... Because the above fix is working only with a System chrome-sandbox setup.

David

**Comment by fortuna** [comment] 2020-11-10 05:17
Duplicate of https://github.com/Jigsaw-Code/outline-client/issues/870

**Closed by fortuna** 2020-11-10 05:17 UTC
Labels: os/linux
