### ISSUE TITLE
Allow user to select the DNS resolver

### ISSUE THREAD

**Issue by JonathanDCohen** [Jigsaw-Code/outline-client#1014] opened 2021-04-28 16:38 UTC
Currently we use the system resolver to resolve the access key hostname and then use a hardcoded list of DNS resolver IPs.  

Some users (eg https://github.com/Jigsaw-Code/outline-server/issues/872) could make use of choosing their own resolver.  We could support this in the UI.

**Comment by williamgh2019** [comment] 2021-06-22 10:14
It is available yet? Than I could use outline and resolve my own DNS server to access my corporate network.

**Comment by bchiarini2** [comment] 2022-07-08 19:59
Ideally we would want to set the DNS on the server.

**Comment by maddyhof** [comment] 2023-06-06 19:33
Closing as duplicate of #568

**Closed by maddyhof** 2023-06-06 19:33 UTC
Labels: feature request, backlog
