### ISSUE TITLE
Error Enabling/Disabling the VPN in iPhone settings

### ISSUE THREAD

**Issue by whitehatqq** [Jigsaw-Code/outline-client#1752] opened 2023-10-11 12:16 UTC
https://github.com/Jigsaw-Code/outline-client/assets/94949898/6c6aa3a1-2ded-4fc7-a410-548783fd5b93

**Comment by jyyi1** [comment] 2023-10-17 19:44
This is reproducible on our end, thanks for reporting this.

**Comment by maddyhof** [comment] 2023-10-23 20:04
Closing as duplicate of #1444

**Closed by maddyhof** 2023-10-23 20:04 UTC
Labels: feature request, os/ios
