### ISSUE TITLE
M1 mac support?

### ISSUE THREAD

**Issue by wyntrson** [Jigsaw-Code/outline-client#1419] opened 2022-10-04 00:22 UTC
It has been years but outline didn’t update the mac client to support Apple Silicon devices.

**Comment by zhqu1148980644** [comment] 2022-11-13 12:33
My M2 mac works, you can install from app store.

**Comment by gut4** [comment] 2023-01-04 17:21
https://github.com/Jigsaw-Code/outline-client/issues/940

**Comment by fortuna** [comment] 2023-01-12 20:26
Duplicate of https://github.com/Jigsaw-Code/outline-client/issues/940

**Closed by fortuna** 2023-01-12 20:26 UTC
Labels: feature request

**Comment by steveg-sjg** [comment] 2023-07-23 17:46
Use the ShadowSock client it works on M1/M2 and connects to Outline Servers as they use the same protocol, also import Outline keys for connections. https://shadowsocks.org/ https://github.com/shadowsocks/ShadowsocksX-NG/releases
