### ISSUE TITLE
Custom DNS Support

### ISSUE THREAD

**Issue by specter78** [Jigsaw-Code/outline-client#1036] opened 2021-06-06 16:11 UTC
**What would you like the app to enable you to do?**
I want to use DNS with adblocking capability with Outline.

**Describe alternatives you've considered**
NA

**Additional context**
Any workaround to use custom dns with outline results in DNS leak, which is not good for stated objective of Outline.

Inbuilt custom DNS support would greatly help.

**Comment by bemasc** [comment] 2022-04-20 14:26
Duplicate of #568

**Closed by bemasc** 2022-04-20 14:26 UTC
Labels: feature request
