### ISSUE TITLE
Connect to Chromecast while running outline-client

### ISSUE THREAD

**Issue by muhammadtarek** [Jigsaw-Code/outline-client#71] opened 2018-04-21 13:02 UTC
Whenever I run outline-client I can't connect to Chromecast. Is there any workaround to fix this?

**Comment by shaomeng** [comment] 2018-04-23 21:58
I'm afraid not, because your device is exposed to the VPN network, instead of local network when outline is on. This behavior is described in the outline FAQ:
- Will I be able to connect to devices in my wifi network if I'm using Outline?
    - No. While running Outline, you won’t be able to connect to devices (e.g. your chromecast, local printer, shared hard drives, etc) that are only accessible from within your local wifi network.

**Comment by cybort** [comment] 2018-04-25 11:47
Maybe you can try the original Shadowsocks client, which allows you to only route messages to some addresses, and let others pass out of the VPN, particularly it can make messages to local network not use VPN.
The key begin with ss:// is compatible with different shadowsocks clients.

**Comment by muhammadtarek** [comment] 2018-04-25 20:38
@cybort @alalamav Thanks for the clarification

**Comment by andreimatei** [comment] 2018-05-28 02:41
And yet I'm able to stream to my Chromecast from my OS X device even though I'm definitely connected to an Outline server with the Outline client... Is that surprising?

**Comment by trevj** [comment] 2018-07-25 20:40
@muhammadtarek Thanks for trying Outline! Bypassing local addresses is something we'd like to address, though we haven't gotten around to it yet.

@andreimatei Yes, it is a little surprising to me that that works.

BTW, I will close this issue as a duplicate of this one (will note that Chromecast is affected):
https://github.com/Jigsaw-Code/outline-client/issues/18

**Closed** 2018-07-25 20:40 UTC
Labels: duplicate
